### ISSUE TITLE
It crashes with GNU Emacs's lsp-mode

### ISSUE THREAD

**Issue by MasWag** [monaqa/satysfi-language-server#1]
It seems satysfi-language-server crashes with lsp-mode of GNU Emacs. The following shows the error log. Maybe you need to add an error handling.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/util.rs:62:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by monaqa** [comment]
Thanks for the report. It seems that getting the cursor position (converting from row and column index to byte index) is failing.

- Could you please send me the file that reproduces this?
- What operation did you perform that caused the error? (start the server, save a file, try to complete a word, etc.)

**Comment by MasWag** [comment]
I am very sorry but after re-compiling the language server, it seems this issue stoped. Sorry again for bothering you.
